services:
  postgres:
    image: postgis/postgis:14-3.5-alpine
    ports:
      #- "5432:5432"
      - "5400:5400"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init_postgis.sql:/docker-entrypoint-initdb.d/init_postgis.sql
    env_file:
      - ./${ENV-dev}.env
    networks:
      - donate-network

  django-app:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
    env_file:
      - ./${ENV-dev}.env
    depends_on:
      - postgres
    networks:
      - donate-network

  # nginx:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - django-app
  #   networks:
  #     - donate-network

networks:
  donate-network:
    driver: bridge